swagger: '2.0'
info:
  title: Meeting Scheduler API
  contact:
    name: API Support
    email: zednis@rpi.edu
  version: 1.0.0
schemes:
  - http
produces:
  - application/json
tags:
- name: Meetings
- name: Users
- name: Room
paths:

  /api/room:

    post:
      summary: Create Meeting Room Record
      parameters:
        - name: create meeting room request object
          in: body
          description: create meeting room request object
          required: true
          schema:
            $ref: "#/definitions/CreateMeetingRoomRequest"
      tags:
      - Room
      responses:
        201:
          description: Created
          headers:
            Location:
              description: relative URL to created meeting room record
              type: string
          schema:
            $ref: "#/definitions/ActionResponse"

    get:
      summary: Retrieve List of Meeting Room Records
      tags:
        - Room
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/ListOfMeetingRoomInfo"

  /api/room/{roomName}:

    get:
      summary: Retrieve Meeting Room Record
      parameters:
        - $ref: "#/parameters/roomName"
      tags:
        - Room
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/MeetingRoomInfo"

    put:
      summary: Update Meeting Room Record
      parameters:
        - $ref: "#/parameters/roomName"
      tags:
        - Room
      responses:
        200:
          description: OK

    delete:
      summary: Delete Meeting Room Record
      parameters:
        - $ref: "#/parameters/roomName"
      tags:
        - Room
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/ActionResponse"


  /api/room/{roomName}/meetings:

    get:
      summary: Retrieve List of Meeting Records for Meeting Room
      parameters:
        - $ref: "#/parameters/roomName"
      tags:
        - Room
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/ListOfMeetingInfo"

  /api/user:

    post:
      summary: Create User Record
      parameters:
        - name: create user request object
          in: body
          description: create user request object
          required: true
          schema:
            $ref: "#/definitions/CreateUserRequest"
      tags:
        - Users
      responses:
        201:
          description: Created
          headers:
            Location:
              description: relative URL to created user record
              type: string
          schema:
            $ref: "#/definitions/ActionResponse"

    get:
      summary: Retrieve List of User Records
      tags:
        - Users
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/ListOfUserInfo"


  /api/user/{userId}:

    get:
      summary: Retrieve User Record
      parameters:
        - $ref: "#/parameters/userId"
      tags:
        - Users
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/UserInfo"

    delete:
      summary: Delete User Record
      parameters:
        - $ref: "#/parameters/userId"
      tags:
        - Users
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/ActionResponse"


  /api/user/{userId}/meetings:

    get:
      summary: Retrieve List of Meeting Records for User
      parameters:
        - $ref: "#/parameters/userId"
      tags:
        - Users
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/ListOfMeetingInfo"

  /api/meeting:

    post:
      summary: Create Meeting Record
      parameters:
        - name: create meeting request object
          in: body
          description: create meeting request object
          required: true
          schema:
            $ref: "#/definitions/CreateMeetingRequest"
      tags:
        - Meetings
      responses:
        201:
          description: Created
          headers:
            Location:
              description: relative URL to created meeting record
              type: string
          schema:
            $ref: "#/definitions/ActionResponse"

  /api/meeting/{meetingId}:

    get:
      summary: Retrieve Meeting Record
      parameters:
      - $ref: "#/parameters/meetingId"
      tags:
       - Meetings
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/MeetingInfo"

    put:
      summary: Update Meeting Record
      parameters:
      - $ref: "#/parameters/meetingId"
      - name: meeting object
        in: body
        description: meeting description
        required: true
        schema:
          $ref: "#/definitions/MeetingInfo"
      tags:
      - Meetings
      responses:
        200:
          description: OK

    delete:
      summary: Delete Meeting Record
      parameters:
      - $ref: '#/parameters/meetingId'
      tags:
       - Meetings
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/ActionResponse"

parameters:

  roomName:
    name: roomName
    in: path
    description: meeting room name
    required: true
    type: string

  meetingId:
    name: meetingId
    in: path
    description: meeting identifier
    required: true
    type: string

  userId:
    name: userId
    in: path
    description: user identifier
    required: true
    type: string


definitions:

  CreateMeetingRoomRequest:
    type: object
    properties:
      name:
        type: string
      resources:
        type: array
        items:
          type: string
    required:
      - name
      - resources

  ActionResponse:
    type: object
    properties:
      requestURL:
        type: string
      action:
        type: string
      status:
        type: number
      message:
        type: string
      timestamp:
        type: string
        format: date-time
    required:
      - requestURL
      - action
      - status
      - message
      - timestamp

  MeetingRoomInfo:
    type: object
    properties:
      name:
        type: string
      resources:
        type: array
        items:
          type: string
      createdAt:
        type: string
        format: date-time
    required:
      - name
      - resources
      - createdAt

  ListOfMeetingRoomInfo:
    type: object
    properties:
      rooms:
        type: array
        items:
          $ref: "#/definitions/MeetingRoomInfo"
    required:
      - rooms

  CreateUserRequest:
    type: object
    properties:
      givenName:
        type: string
      familyName:
        type: string
      email:
        type: string
    required:
      - givenName
      - familyName
      - email

  UserInfo:
    type: object
    properties:
      userId:
        type: string
      givenName:
        type: string
      familyName:
        type: string
      email:
        type: string
      createdAt:
        type: string
        format: date-time
    required:
      - userId
      - givenName
      - familyName
      - email
      - createdAt

  ListOfUserInfo:
    type: object
    properties:
      users:
        type: array
        items:
          $ref: "#/definitions/UserInfo"
    required:
      - users

  CreateMeetingRequest:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      startDateTime:
        type: string
        format: date-time
      endDateTime:
        type: string
        format: date-time
    required:
      - name
      - startDateTime
      - endDateTime

  MeetingInfo:
    type: object
    properties:
      meetingId:
        type: string
      name:
        type: string
      description:
        type: string
      startDateTime:
        type: string
        format: date-time
      endDateTime:
        type: string
        format: date-time
      createdAt:
        type: string
        format: date-time
    required:
      - meetingId
      - name
      - startDateTime
      - endDateTime
      - createdAt

  ListOfMeetingInfo:
    type: object
    properties:
      meetings:
        type: array
        items:
          $ref: "#/definitions/MeetingInfo"
    required:
      - meetings