branch-defaults:
  aws-deployment:
    environment: meeting-scheduler
environment-defaults:
  meeting-scheduler:
    branch: null
    repository: null
global:
  application_name: meeting-scheduler
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Node.js running on
    64bit Amazon Linux/4.4.5
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
